#!/bin/bash

USERID=$(id -u) # id -u is to check ID of the user (u) and store in USERID variable

if [ $USERID -ne 0 ] # if USERID is not 0 then user doesnot have root access so give error
then
    echo "ERROR:: You must have sudo access to execute this script"
    exit 1 #other than 0
fi

dnf list installed mysql # to check what mysql packages are installed 

if [ $? -ne 0 ] # $? command is to check last command status called exit status 
then # not installed
    dnf install mysql -y # command to instal Mysql
    if [ $? -ne 0 ]
    then
        echo "Installing MySQL ... FAILURE"
        exit 1
    else
        echo "Installing MySQL ... SUCCESS"
    fi
else
    echo "MySQL is already ... INSTALLED"
fi



dnf list installed git

if [ $? -ne 0 ]
then
    dnf install git -y # command to instal Git
    if [ $? -ne 0 ]
    then
        echo "Installing Git ... FAILURE"
        exit 1
    else
        echo "Installing Git ... SUCCESS"
    fi
else
    echo "Git is already ... INSTALLED"
fi
